[package]
name = "proto_array"
version = "0.2.0"
authors = ["Paul Hauner <paul@sigmaprime.io>"]
edition = "2021"

[[bin]]
name = "proto_array"
path = "src/bin.rs"

[dependencies]
types = { path = "../types" }
ethereum_ssz = "1.0.0-beta.2"
ethereum_ssz_derive = "1.0.0-beta.2"
serde = "1.0.116"
serde_derive = "1.0.116"
serde_yaml = "0.8.13"
safe_arith = { path = "../safe_arith" }
